/**
 * /coherence:enable-sidecars — provision sidecar YAML files for skills/agents
 * when the host strips unknown frontmatter keys.
 * FR-COMMANDS-7, DD-043
 */
import { mkdirSync, writeFileSync, existsSync, readdirSync, readFileSync } from 'fs';
import path from 'path';

export interface EnableSidecarsOptions {
  projectRoot: string;
}

export interface SidecarResult {
  provisioned: string[];
  skipped: string[];
  message: string;
}

function parseFrontmatterName(content: string): string | null {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return null;
  const nameMatch = match[1].match(/^name:\s*(.+)$/m);
  return nameMatch ? nameMatch[1].trim() : null;
}

function buildSidecarYaml(name: string, sectionRef: string): string {
  return [
    `# coherence sidecar for ${name}`,
    `# Auto-generated by /coherence:enable-sidecars`,
    `# This file preserves coherence frontmatter keys when the host strips them.`,
    `name: ${name}`,
    `coherence:section: ${sectionRef}`,
    ``,
  ].join('\n');
}

// eslint-disable-next-line @typescript-eslint/require-await -- async public API; future implementations may await IO
export async function runEnableSidecars(opts: EnableSidecarsOptions): Promise<SidecarResult> {
  const provisioned: string[] = [];
  const skipped: string[] = [];

  const claudeDir = path.join(opts.projectRoot, '.claude');
  const sidecarsDir = path.join(claudeDir, 'coherence', 'sidecars');
  mkdirSync(sidecarsDir, { recursive: true });

  // Scan for skill/agent files in .claude/
  const skillDirs = ['skills', 'agents', 'commands'].map((d) => path.join(claudeDir, d));

  for (const dir of skillDirs) {
    if (!existsSync(dir)) continue;
    const entries = readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(dir, entry.name);
      const skillFile = path.join(skillDir, 'SKILL.md');
      const agentFile = path.join(skillDir, 'AGENT.md');
      const targetFile = existsSync(skillFile) ? skillFile : existsSync(agentFile) ? agentFile : null;

      if (!targetFile) continue;

      const content = readFileSync(targetFile, 'utf8');
      const name = parseFrontmatterName(content) ?? entry.name;
      const sectionRef = `${path.relative(opts.projectRoot, targetFile).replace(/\\/g, '/')}#${name}`;

      const sidecarPath = path.join(sidecarsDir, `${entry.name}.yaml`);
      if (existsSync(sidecarPath)) {
        skipped.push(entry.name);
        continue;
      }

      writeFileSync(sidecarPath, buildSidecarYaml(name, sectionRef), 'utf8');
      provisioned.push(entry.name);
    }
  }

  const lines = ['[coherence] enable-sidecars:'];
  if (provisioned.length > 0) {
    lines.push(`  Provisioned ${provisioned.length} sidecar(s): ${provisioned.join(', ')}`);
  }
  if (skipped.length > 0) {
    lines.push(`  Skipped ${skipped.length} (already exist): ${skipped.join(', ')}`);
  }
  if (provisioned.length === 0 && skipped.length === 0) {
    lines.push('  No skill/agent directories found in .claude/');
  }

  return { provisioned, skipped, message: lines.join('\n') };
}
