#!/usr/bin/env node
/**
 * Atomic version bump across all 7 sources of truth.
 *
 * Usage:
 *   node scripts/bump.mjs <new-version>
 *
 * Sources updated (must all stay in lockstep — enforced by
 * scripts/release-ga.mjs#assertVersionSync):
 *   1. package.json#version
 *   2. package-lock.json#version
 *   3. .claude-plugin/plugin.json#version
 *   4. .claude-plugin/marketplace.json#plugins[0].version
 *   5. .claude-plugin/marketplace.json#plugins[0].source.ref  (prefixed with "v")
 *   6. src/state/init.ts#PLUGIN_VERSION literal
 *   7. README cosign-verify block — regenerated by `npm run build`
 *      via scripts/render-readme-verification.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const SEMVER_RE = /^\d+\.\d+\.\d+(?:[-+][\w.-]+)?$/;

const DEFAULT_PATHS = {
  packageJsonPath: 'package.json',
  packageLockPath: 'package-lock.json',
  pluginJsonPath: '.claude-plugin/plugin.json',
  marketplaceJsonPath: '.claude-plugin/marketplace.json',
  initTsPath: 'src/state/init.ts',
};

export function bumpAllSources(version, paths = DEFAULT_PATHS) {
  if (!SEMVER_RE.test(version)) {
    throw new Error(`Not a valid semver string: ${version}`);
  }

  const pkg = JSON.parse(readFileSync(paths.packageJsonPath, 'utf8'));
  pkg.version = version;
  writeFileSync(paths.packageJsonPath, JSON.stringify(pkg, null, 2) + '\n');

  const lock = JSON.parse(readFileSync(paths.packageLockPath, 'utf8'));
  lock.version = version;
  if (lock.packages?.['']) lock.packages[''].version = version;
  writeFileSync(paths.packageLockPath, JSON.stringify(lock, null, 2) + '\n');

  const plugin = JSON.parse(readFileSync(paths.pluginJsonPath, 'utf8'));
  plugin.version = version;
  writeFileSync(paths.pluginJsonPath, JSON.stringify(plugin, null, 2) + '\n');

  const market = JSON.parse(readFileSync(paths.marketplaceJsonPath, 'utf8'));
  market.plugins[0].version = version;
  market.plugins[0].source.ref = `v${version}`;
  writeFileSync(paths.marketplaceJsonPath, JSON.stringify(market, null, 2) + '\n');

  const initTs = readFileSync(paths.initTsPath, 'utf8');
  const updated = initTs.replace(
    /(export const PLUGIN_VERSION\s*=\s*)['"][^'"]+['"]/,
    `$1'${version}'`,
  );
  if (updated === initTs) {
    throw new Error(`Failed to find PLUGIN_VERSION literal in ${paths.initTsPath}`);
  }
  writeFileSync(paths.initTsPath, updated);
}

if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] ?? '')) {
  const target = process.argv[2];
  if (!target) {
    console.error('Usage: node scripts/bump.mjs <new-version>');
    process.exit(1);
  }
  bumpAllSources(target);
  console.log(`[bump] all 7 sources now at ${target}. Run \`npm run build\` to regenerate README cosign block.`);
}
